insert into fauna(name, avg_age) values ('cat', 5000);
insert into fauna(name, avg_age) values ('dog', 4000);
insert into fauna(name, avg_age) values ('whitefish', 3000);
insert into fauna(name, avg_age) values ('horse', 16000);
insert into fauna(name, avg_age, discovery_date) values ('leopardus tigrinus guttulus', 2000, '2013-01-01');
insert into fauna(name, avg_age, discovery_date) values ('alaskan hare', 2000, '1900-01-01');
select * from fauna where name like '%fish%';
select * from fauna where avg_age >= 10000 and avg_age <= 21000;
select * from fauna where discovery_date is null;
select * from fauna where discovery_date < '1950-01-01';